/* 
 * @project.name@
 *
 * @project.description@
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Au.Client.SwaggerDateConverter;

namespace IO.Swagger.Au.Model
{
    /// <summary>
    /// Asl
    /// </summary>
    [DataContract]
    public partial class Asl :  IEquatable<Asl>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Asl" /> class.
        /// </summary>
        /// <param name="descrizioneASL">descrizioneASL.</param>
        /// <param name="flagAnnullato">flagAnnullato.</param>
        /// <param name="uUID">uUID.</param>
        public Asl(string descrizioneASL = default(string), string flagAnnullato = default(string), string uUID = default(string))
        {
            this.DescrizioneASL = descrizioneASL;
            this.FlagAnnullato = flagAnnullato;
            this.UUID = uUID;
        }
        
        /// <summary>
        /// Gets or Sets DescrizioneASL
        /// </summary>
        [DataMember(Name="descrizioneASL", EmitDefaultValue=false)]
        public string DescrizioneASL { get; set; }

        /// <summary>
        /// Gets or Sets FlagAnnullato
        /// </summary>
        [DataMember(Name="flagAnnullato", EmitDefaultValue=false)]
        public string FlagAnnullato { get; set; }

        /// <summary>
        /// Gets or Sets UUID
        /// </summary>
        [DataMember(Name="uUID", EmitDefaultValue=false)]
        public string UUID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Asl {\n");
            sb.Append("  DescrizioneASL: ").Append(DescrizioneASL).Append("\n");
            sb.Append("  FlagAnnullato: ").Append(FlagAnnullato).Append("\n");
            sb.Append("  UUID: ").Append(UUID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Asl);
        }

        /// <summary>
        /// Returns true if Asl instances are equal
        /// </summary>
        /// <param name="input">Instance of Asl to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Asl input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DescrizioneASL == input.DescrizioneASL ||
                    (this.DescrizioneASL != null &&
                    this.DescrizioneASL.Equals(input.DescrizioneASL))
                ) && 
                (
                    this.FlagAnnullato == input.FlagAnnullato ||
                    (this.FlagAnnullato != null &&
                    this.FlagAnnullato.Equals(input.FlagAnnullato))
                ) && 
                (
                    this.UUID == input.UUID ||
                    (this.UUID != null &&
                    this.UUID.Equals(input.UUID))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DescrizioneASL != null)
                    hashCode = hashCode * 59 + this.DescrizioneASL.GetHashCode();
                if (this.FlagAnnullato != null)
                    hashCode = hashCode * 59 + this.FlagAnnullato.GetHashCode();
                if (this.UUID != null)
                    hashCode = hashCode * 59 + this.UUID.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
